version: '3.8'

services:
  database:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Mount thư mục data
    ports:
      - "8000:8000"

  frontend: # <-- BẠN CHỈ CẦN CHỈNH SỬA KHỐI NÀY
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000

volumes:
  postgres_data: